### ISSUE TITLE
When joining with dimensions, use the latest partition

### ISSUE THREAD

**Issue by betodealmeida** [DataJunction/datajunction#112]
We currently require users to annotate dimension nodes. Should we use the latest (time) partition when doing a join with the node?

**Comment by betodealmeida** [comment]
Depends on https://github.com/DataJunction/datajunction/issues/121.

**Comment by betodealmeida** [comment]
We could also change the syntax of source nodes to declare how the dimension join should happen:

```yaml
description: A fact table with comments
type: source
columns:
  id:
    type: INT
  user_id:
    type: INT
    dimension:
      column: core.users.id
      partition: core.users.ds@latest
      freshness: 7 days
```
