### ISSUE TITLE
Add support for partitions

### ISSUE THREAD

**Issue by betodealmeida** [DataJunction/datajunction#121]

**Comment by betodealmeida** [comment]
This has to be implemented per-DB. For Postgres: https://dba.stackexchange.com/questions/223327/how-to-identify-the-column-used-to-partition-a-table-from-the-postgres-system-ca

**Comment by betodealmeida** [comment]
Some work started here: https://github.com/DataJunction/datajunction/compare/partitions

**Comment by agorajek** [comment]
Let's consider the following use cases for partitions in DJ:

1. Partition as a filter, for efficient data querying. 
    Example: a query referencing DJ nodes is generated by DJ to run on some database. 
    This can apply to both source nodes and transform nodes, that is tables managed by DJ and outside of DJ control.

2. Partition for data management, for efficient data storage and access.
    A DDL/insert statement is generated by DJ to create or load a materialized version of a DJ node.

The 1st use case requires two features:
- ability to recognize partition features in tables corresponding to source nodes
- ability to translate DJ queries into partition filters, they should not be different than regular column filter

The 2nd use case is much more involved:
- ability to let the users add a partitioning scheme at the DJ repo level and at the DJ node level.
- ability to create proper DDL and insert/load statements with the correct partition values

Lets consider the following partition spec for DJ world:
```
partitions:
  - name: <string>
    type: [date, str, int]
    value | interval: day, month, year, etc (optional) 
    tz: ISO time zone (optional)
    format: YYYYMMDD (optional)
```
