### ISSUE TITLE
Add support for extra parameters when defining a database

### ISSUE THREAD

**Issue by betodealmeida** [DataJunction/datajunction#130]
Currently a database is defined essentially by a `URI` parameter that takes a SQLAlchemy URI. Eg:

https://github.com/DataJunction/datajunction/blob/148793656ecf96b4eb246776bc296feefd314ed4/examples/configs/databases/postgres.yaml#L1-L4

Some databases like BigQuery might require parameters that are hard to express in the URI, like `credentials_info`. We need to change the `Database` model so that it has an `extra_params` field:

```yaml
description: A Postgres database
URI: postgresql://username:FoolishPassword@host.docker.internal:5433/examples
extra_params:
  connect_args:
    ssl_mode: require
read_only: false
cost: 10
```

This needs to be added to the model, and also passed to `create_engine`.
