### ISSUE TITLE
Watchdog should not die when compile fails

### ISSUE THREAD

**Issue by betodealmeida** [DataJunction/datajunction#192]

**Comment by samredai** [comment]
I think we can fix this simply by adding `restart: on-failure` to the watchdog service.
```
  watchdog:
    container_name: watchdog
    restart: on-failure
    environment:
      - DOTENV_FILE=.env-docker
    build: .
    volumes:
      - .:/code
    depends_on:
      - dj
    command: dj compile --reload
```
