### ISSUE TITLE
Add support for dimensions

### ISSUE THREAD

**Issue by betodealmeida** [DataJunction/datajunction#45]
We should be able to annotate nodes as being dimensions (eg, [user.yaml](https://github.com/DataJunction/datajunction/blob/main/examples/configs/nodes/core/users.yaml) in the examples), and reference them in other nodes.

When a node has a dimension node associated with it users should be able to group by/filter columns in the dimension, eg:

```sql
SELECT "core.num_comments"
FROM metrics
WHERE "core.users.preferred_language" = 'Spanish'
```

Or with the REST API:

```bash
$ curl "http://localhost:8000/metrics/6/data/?f=core.users.preferred_language='Spanish'"
```

One thing to consider is if we should automap dimensions based on the DB schema. For example, if a DB has two tables, "users" and "comments", and a user creates two nodes for them:

```yaml
# comments.yaml
description: A fact table with comments
tables:
  postgres:
    - catalog: null
      schema: public
      table: comments
columns:
  user_id:
    type: int
```

```yaml
# users.yaml
description: A user dimension table
type: dimension
tables:
  postgres:
    - catalog: null
      schema: public
      table: users
columns:
  id:
    type: int
```

If we infer from the database that `comments.user_id` is a foreign key to `users.id` we could automatically annotate that in the `comments.yaml` file:

```yaml
# comments.yaml
description: A fact table with comments
tables:
  postgres:
    - catalog: null
      schema: public
      table: comments
columns:
  user_id:
    type: int
    dimension: users  # <= here
```
