### ISSUE TITLE
Virtual dimensions

### ISSUE THREAD

**Issue by betodealmeida** [DataJunction/datajunction#63]
We should implement virtual dimensions like time, space, or user-defined. For example, if we have a table with timestamps we should be able to annotate the temporal column as belonging to the "time" dimension:

```YAML
description: An event table
tables:
  postgres:
    - catalog: null
      schema: public
      table: comments
      columns:
        - event_time:
          type: timestamp
          dimension: time
```

Once we've done that, a bunch of virtual dimensions can be used. For example, we should be able to group by the dimension `time.day_of_week`, or filter out `time.us_holidays`.
