### ISSUE TITLE
Allow adding extra metadata to nodes

### ISSUE THREAD

**Issue by betodealmeida** [DataJunction/datajunction#65]
When we run `dj compile` it would be nice if the command wrote back to the YAML files the information retrieved about columns. This would allow users to easily add extra metadata to nodes. For example, if we have the following source node:

```yaml
description: A fact table with comments
tables:
  postgres:
    - catalog: null
      schema: public
      table: comments
```

Running `dj compile` could update the YAML file with column information:

```yaml
description: A fact table with comments
tables:
  postgres:
    - catalog: null
      schema: public
      table: comments
columns:
  ds:
    type: string
  id:
    type: int
```

So that the user can easily add metadata to the columns, eg:

```yaml
description: A fact table with comments
tables:
  postgres:
    - catalog: null
      schema: public
      table: comments
columns:
  ds:
    type: string
    dimension: time  # <= here
  id:
    type: int
```
