### ISSUE TITLE
Command to add databases

### ISSUE THREAD

**Issue by betodealmeida** [DataJunction/datajunction#98]
We could have a command to add databases:

```bash
% dj add-database dev.test_db sqlite:////tmp/file.db --description="A simple SQLite database" --cost=10
```

This would create the file `dev/test_db.yaml` with the configuration for the database:

```yaml
description: A simple SQLite database
URI: sqlite:////tmp/file.db
read_only: false
cost: 10
```
